name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: dotnet build
    - name: Unit Test
      run: |
        dotnet test
    - name: Publish to Nuget
      run: |
        dotnet pack --configuration Release
        pwd
        ls
        dotnet nuget push ./RsaThreeDeeSecure/bin/Debug/RsaThreeDeeSecure.1.0.0.nupkg -k ${{ secrets.nuget_token }} -s https://api.nuget.org/v3/index.json
